services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skippyapi-php
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=skippyapi
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - eoooio_network

  mariadb:
    image: mariadb:latest
    container_name: skippyapi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skippyapi
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - eoooio_network

volumes:
  mariadb_data:
    driver: local

networks:
  eoooio_network:
    driver: bridge